# Generated by Django 4.2 on 2023-05-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.CharField(max_length=50)),
                ('imsak', models.TimeField()),
                ('subuh', models.TimeField()),
                ('tebit', models.TimeField()),
                ('duha', models.TimeField()),
                ('zuhur', models.TimeField()),
                ('asar', models.TimeField()),
                ('magrib', models.TimeField()),
                ('isya', models.TimeField()),
            ],
        ),
    ]
